### PR TITLE
Perlin -> Simplex/Perlin/Gradient, domain rotation, 3D noise mode, other tweaks

### PR DESCRIPTION
**Pull request by KdotJPG**
* Replaced instances of Perlin noise with Simplex-type noise, to promote the use of newer tools with better directional variety characteristics.
* Updated type names to reference the more general category of Gradient noise, under which Simplex and Perlin both fall.
* Added a 3D noise mode to the newly-dubbed `GradientNoiseScene`, which scrolls along the third coordinate instead of diagonally along the first two.
* Updated README in correspondence to the changes.
* Various style and consistency tweaks (mostly using Visual Studio's auto-format feature on entire files).

Let me know if there's anything I should adjust, add, or revert so that it best fits your vision!

bild
bild
bild

### CODE REVIEW

**Comment by Sokkero** [comment]
Hay, thank you very much for contributing. I would love to add Simplex to the repo, but sadly the PR is barely readable currently. Would it be possible for you to split the diff into smaller commits and also remove the styling changes?

**Comment by Sokkero** [comment]
Also, just a thought: I personally think I would prefer the Simplex generation to be its own scene next to the perlin & voronoi scene. As this is more extra work I cannot expect you to do everything, so if you want I can also do that (obviously adding you to the README.md as contributer).

**Comment by KdotJPG** [comment]
I can redo the commits and whatnot, sure.

After removing the auto-styling, what format would you prefer my actual code contributions to be in? I noticed multiple coding styles in the various files, including
```
if (something) {
}
```
```
if(something){
}
```
and
```
if (something)
{
}
```
which is what originally inspired me to run the formatter. Alternatively, if you do have a preferred overall style, I could try to configure an auto-format profile for it then include that as the final commit, if you would still like.

Re: keeping both gradient noises, what would you think about still keeping one 'Gradient Noise` scene, and just adding both noises with a toggle keybind + maybe indicator text? The noise types serve essentially the same purpose, just with the differences I had mentioned. IMO that approach would better present all of that, with also less code duplication.

And I don't mind re-doing it, I'll just have to see when I can get to it in the next few days. :thumbsup:

**Comment by Sokkero** [comment]
I dont mind the code formatting, its just crowding the PR, making it barely readable. It would be alright if you seperate it into its own commit (the second style of what you mentioned).

I believe that having an own scene for Simplex would be the best way to go as to not create confusion. I am planning on adding detailed readme's to each scene, describing what is happening as well.

Also no stress, I dont have much time the next few days as well ^^

**Comment by Sokkero** [comment]
Hello @KdotJPG, I just wanted to quickly check in and ask if you are still intered in adding this feature to the project. If not then please let me know so that I can close this PR and work on this myself (so that I also learn about this ^^).

**Comment by KdotJPG** [comment]
Yes! My bad, I fell a bit out of the swing over the past few weeks. Give me until tonight or tomorrow and I will have something to update this with.

**Comment by KdotJPG** [comment]
Ok, I have the majority of changes in. I didn't include the dedicated code style commit yet, since I want to confirm your preference for no spacing between keywords+parentheses / parentheses+braces.

`if(something){` isn't a common style I see, and can appear a bit cluttered in my view. The most common I see for C# is essentially [Allman Style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) and what I typically use (for both C# and Java) is [K&R Variant: Java](https://en.wikipedia.org/wiki/Indentation_style#Variant:_Java).

Happy to do whichever, though.

(Update: also updated README.md, let me know if there's anything I should change about those changes there)

**Comment by Sokkero** [comment]
Hello, I'm sorry for the late reply.
K&R Variant styling is fine with me. 
I really like your changes but did spot 2 bugs, which are both in the voronoi scene.
1) `The referenced script (treeScript) on this Behaviour is missing!
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion, Transform)` when the tree models are loaded.
2) The trees & cylinders dont align themselves with the terrain height when the gradient noise is applied.

**Comment by Sokkero** [comment]
Quick update: the two bugs were related to a naming issue that I just fixed. If you want to you can now add your styling and I will merge. 
Thank you for helping me grow this small project!

**Comment by KdotJPG** [comment]
Code styling is in! Realizing now that it may not have produced an update notification.

**Review by Sokkero — APPROVED** [review]

**Comment by Sokkero** [comment]
Sorry for taking so long (been busy with work). Now merged though 👍

**Pull request merged**
